# Generated by Django 6.0.1 on 2026-02-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'SocialLink'},
        ),
    ]
